DROP TABLE IF EXISTS Pago CASCADE;
DROP TABLE IF EXISTS Tiene_servicio CASCADE;
DROP TABLE IF EXISTS Cuesta CASCADE;
DROP TABLE IF EXISTS pagado CASCADE;
DROP TABLE IF EXISTS Llamada CASCADE;
DROP TABLE IF EXISTS Pago_Automatico CASCADE;
DROP TABLE IF EXISTS Pago_Por_Oficina CASCADE;
DROP TABLE IF EXISTS Cheque CASCADE;
DROP TABLE IF EXISTS Contrato CASCADE;
DROP TABLE IF EXISTS Persona_Natural CASCADE;
DROP TABLE IF EXISTS Persona_Juridica CASCADE;
DROP TABLE IF EXISTS Suscriptor CASCADE;
DROP TABLE IF EXISTS Sucursal CASCADE;
DROP TABLE IF EXISTS Pais CASCADE;
DROP TABLE IF EXISTS Destino CASCADE;
DROP TABLE IF EXISTS Servicio CASCADE;
DROP TABLE IF EXISTS Tipo_Renta CASCADE;
DROP TABLE IF EXISTS Compania_Celular CASCADE;
DROP TABLE IF EXISTS Impuesto CASCADE;


DELETE FROM Pago;